= {feelpp} Data Files 

{feelpp} generates various files that are spread over various directories.
For this tutorial, it would be beneficial to check the content of these files
to familiarize yourself with {feelpp}. 

== Environment variables

The environment variable `FEELPP_REPOSITORY` define the root directory where the simulation results will be stored. 
By default they are set to `$HOME/feel`. 

If you want to change the root directory where the results are stored, define e.g. `FEELPP_REPOSITORY`. 

IMPORTANT: in {feelpp} docker images, such as `feel/feelpp`, it points to `/feel`.

For running,
[source,shell]
----
docker run -it -v $HOME/feel:/feel feelpp/feelpp
----
should get you this output
[source,shell]
----
feelpp@50381de2bd23:~$ 
----

and here is the result of `echo $FEELPP_REPOSITORY` in the docker image
[source,shell]
----
feelpp@50381de2bd23:~$ echo $FEELPP_REPOSITORY 
/feel
----

== Results

Results of {feelpp} simulations are stored in `$FEELPP_REPOSITORY/feel/<your_app_name>/` or in a sub-directory.
The name of the directory is `np_<num>` where `num` is the number of processors used by the numerical simulation.

=== Logfiles

Feel++ uses https://github.com/google/glog[Google Glog] to generate logfiles. 
They are stored in  `np_<num>/logs`.
By default, only the master MPI process produces a logfile. 
This can be changed using the option:
|===
| Option | Description | Default value
| disable_log | Disable logfile generation | false
| log_level_process | log level: 2 enable logging for all processes, 1 enable only for master 0 disable for all processes | 1
|===

=== CAD and Meshes

A copy of the mesh and eventually the CAD can be found in  `np_<num>`.

NOTE: the CAD and mesh are present both when GMSH is used to generate a mesh from {feelpp} from a CAD file.



